### ISSUE TITLE
sqlite3.OperationalError: no such table: Documents

### ISSUE THREAD

**Issue by anaknaga** [Xunius/Menotexport#3]
First, thanks for all the hard work. I'm moving to Zotero from Mendeley and I hope your program will be very helpful. However when using it I run into the following error:

`python menotexport.py -pmns ~/.local/share/data/Mendeley\ Ltd./Mendeley\ Desktop/XXXXX@www.mendeley.com.sqlite ~/Downloads/Mendeley_export/
# 

<Menotexport>: Connected to database:

/home/XXXXX/.local/share/data/Mendeley Ltd./Mendeley
    Desktop/XXXXX@www.mendeley.com.sqlite
Traceback (most recent call last):
  File "menotexport.py", line 910, in <module>
    args.separate,args.verbose)
  File "menotexport.py", line 785, in main
    folderlist=getFolderList(db,folder)
  File "menotexport.py", line 596, in getFolderList
    ret=db.execute(query)
sqlite3.OperationalError: no such table: Documents`

`# uname -a
Linux T450s-tumbleweed 4.5.4-1-default #1 SMP PREEMPT Wed May 11 15:23:21 UTC 2016 (db90c25) x86_64 x86_64 x86_64 GNU/Linux`

mendeley version: 1.16.1

(formatting is messed up, not sure exactly why, sorry!)

**Comment by Xunius** [comment]
Hi anaknaga, 
Thanks for checking out this software, and sorry for the late reply: I've been on travelling recently.

I cannot reproduce your error, even after upgrading mendeley to 1.16.1. The error occurred when trying to fetch data from the Mendeley database (in sqlite format), and somehow failed to find a table named "Documents" in the dataset. Considering you are using Mendeley already, the database can't be empty.

Could you check out the sqlite version for me, by launching into a python session `python`, and then

```
import sqlite3
sqlite3.sqlite_version
sqlite3.version
```

Mine are 3.9.2 and 2.6.0, respectively.
If yours are older, please try give them an upgrade, and let me know it works or not.
